POST http://localhost:3333/courses
Content-Type: application/json

{
    "title": "Curso de Cobol"
}

###

GET http://localhost:3333/courses?orderBy=title

###

GET http://localhost:3333/courses/fe0fe958-8a9f-47c9-9f4a-d7eab586ffc4